/*
 * MobileAccess v1.3.0
 *  ##### **NaaS API Version:** 2.4.0 ##### **mobileAccess service version:** 1.2.3 ## OVERVIEW TMF 640 - Activation and Configuration API. This is a strategic mobileAccess service aiming to provide network capabilities to products.   **Note: Enum values are case sensitive**
 *
 * OpenAPI spec version: 2.4.5
 * Contact: D1701045@team.telstra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.client.model.ProcessStatus;
import io.swagger.client.model.SeverityEnum;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Telstra Extension to TMF. Process Status provides additional details on services being transitioned to a new state.  It also provides information on failed transactions. processStatus will be an array.
 */
@Schema(description = "Telstra Extension to TMF. Process Status provides additional details on services being transitioned to a new state.  It also provides information on failed transactions. processStatus will be an array.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-13T11:27:23.768Z[GMT]")
public class ProcessStatus {
  @SerializedName("severity")
  private SeverityEnum severity = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("parameterizedMessage")
  private List<Object> parameterizedMessage = null;

  @SerializedName("timeStamp")
  private String timeStamp = null;

  @SerializedName("code")
  private String code = null;

  public ProcessStatus severity(SeverityEnum severity) {
    this.severity = severity;
    return this;
  }

   /**
   * Get severity
   * @return severity
  **/
  @Schema(required = true, description = "")
  public SeverityEnum getSeverity() {
    return severity;
  }

  public void setSeverity(SeverityEnum severity) {
    this.severity = severity;
  }

  public ProcessStatus message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Message string.
   * @return message
  **/
  @Schema(required = true, description = "Message string.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ProcessStatus parameterizedMessage(List<Object> parameterizedMessage) {
    this.parameterizedMessage = parameterizedMessage;
    return this;
  }

  public ProcessStatus addParameterizedMessageItem(Object parameterizedMessageItem) {
    if (this.parameterizedMessage == null) {
      this.parameterizedMessage = new ArrayList<Object>();
    }
    this.parameterizedMessage.add(parameterizedMessageItem);
    return this;
  }

   /**
   * Array of objects containing parameterized values from message.
   * @return parameterizedMessage
  **/
  @Schema(description = "Array of objects containing parameterized values from message.")
  public List<Object> getParameterizedMessage() {
    return parameterizedMessage;
  }

  public void setParameterizedMessage(List<Object> parameterizedMessage) {
    this.parameterizedMessage = parameterizedMessage;
  }

  public ProcessStatus timeStamp(String timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Timestamp of the message generated and populated by domain.
   * @return timeStamp
  **/
  @Schema(description = "Timestamp of the message generated and populated by domain.")
  public String getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(String timeStamp) {
    this.timeStamp = timeStamp;
  }

  public ProcessStatus code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Unique identification of the message (or error) across all domains. [ Recommendation - include service type also in the code].
   * @return code
  **/
  @Schema(required = true, description = "Unique identification of the message (or error) across all domains. [ Recommendation - include service type also in the code].")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessStatus processStatus = (ProcessStatus) o;
    return Objects.equals(this.severity, processStatus.severity) &&
        Objects.equals(this.message, processStatus.message) &&
        Objects.equals(this.parameterizedMessage, processStatus.parameterizedMessage) &&
        Objects.equals(this.timeStamp, processStatus.timeStamp) &&
        Objects.equals(this.code, processStatus.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(severity, message, parameterizedMessage, timeStamp, code);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessStatus {\n");
    
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    parameterizedMessage: ").append(toIndentedString(parameterizedMessage)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
