/*
 * MobileAccess v1.3.0
 *  ##### **NaaS API Version:** 2.4.0 ##### **mobileAccess service version:** 1.2.3 ## OVERVIEW TMF 640 - Activation and Configuration API. This is a strategic mobileAccess service aiming to provide network capabilities to products.   **Note: Enum values are case sensitive**
 *
 * OpenAPI spec version: 2.4.5
 * Contact: D1701045@team.telstra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.client.model.RelatedService;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Details of the related Object on which \&quot;task\&quot; is executed.
 */
@Schema(description = "Details of the related Object on which \"task\" is executed.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-13T11:27:23.768Z[GMT]")
public class RelatedService {
  @SerializedName("@referredType")
  private String _atReferredType = null;

  @SerializedName("href")
  private String href = null;

  public RelatedService _atReferredType(String _atReferredType) {
    this._atReferredType = _atReferredType;
    return this;
  }

   /**
   * @type of the referred object (E.g., \&quot;service\&quot;, \&quot;serviceProblem\&quot;, etc.). If any of the referred object is extended to a new schema, the name of the new schema must be used (E.g., Domain has extended the \&quot;service\&quot; to \&quot;ucNumbers\&quot;). This attribute is mandatory when the @referredType is not the @type as service, ServiceProblem, serviceSpecification\&quot;
   * @return _atReferredType
  **/
  @Schema(description = "@type of the referred object (E.g., \"service\", \"serviceProblem\", etc.). If any of the referred object is extended to a new schema, the name of the new schema must be used (E.g., Domain has extended the \"service\" to \"ucNumbers\"). This attribute is mandatory when the @referredType is not the @type as service, ServiceProblem, serviceSpecification\"")
  public String getAtReferredType() {
    return _atReferredType;
  }

  public void setAtReferredType(String _atReferredType) {
    this._atReferredType = _atReferredType;
  }

  public RelatedService href(String href) {
    this.href = href;
    return this;
  }

   /**
   * href of the included resource instance
   * @return href
  **/
  @Schema(required = true, description = "href of the included resource instance")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelatedService relatedService = (RelatedService) o;
    return Objects.equals(this._atReferredType, relatedService._atReferredType) &&
        Objects.equals(this.href, relatedService.href);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_atReferredType, href);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelatedService {\n");
    
    sb.append("    _atReferredType: ").append(toIndentedString(_atReferredType)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
