/*
 * MobileAccess v1.3.0
 *  ##### **NaaS API Version:** 2.4.0 ##### **mobileAccess service version:** 1.2.3 ## OVERVIEW TMF 640 - Activation and Configuration API. This is a strategic mobileAccess service aiming to provide network capabilities to products.   **Note: Enum values are case sensitive**
 *
 * OpenAPI spec version: 2.4.5
 * Contact: D1701045@team.telstra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;

import io.swagger.client.model.SeverityEnum;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Indicates if message is informational or indicates an error.
 */
@JsonAdapter(SeverityEnum.Adapter.class)
public enum SeverityEnum {
  INFO("INFO"),
  WARN("WARN"),
  ERROR("ERROR"),
  CRITICAL("CRITICAL");

  private String value;

  SeverityEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SeverityEnum fromValue(String input) {
    for (SeverityEnum b : SeverityEnum.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SeverityEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final SeverityEnum enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public SeverityEnum read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return SeverityEnum.fromValue((String)(value));
    }
  }
}
