/*
 * MobileAccess v1.3.0
 *  ##### **NaaS API Version:** 2.4.0 ##### **mobileAccess service version:** 1.2.3 ## OVERVIEW TMF 640 - Activation and Configuration API. This is a strategic mobileAccess service aiming to provide network capabilities to products.   **Note: Enum values are case sensitive**
 *
 * OpenAPI spec version: 2.4.5
 * Contact: D1701045@team.telstra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.client.model.ResponseHubServiceType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The registration of a listener is done by creating a HUB resource unique to the listener (equivalent of a subscription).
 */
@Schema(description = "The registration of a listener is done by creating a HUB resource unique to the listener (equivalent of a subscription).")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-13T11:27:23.768Z[GMT]")
public class ResponseHubServiceType {
  @SerializedName("id")
  private String id = null;

  @SerializedName("callback")
  private String callback = null;

  @SerializedName("eventType")
  private String eventType = null;

  @SerializedName("createdTime")
  private String createdTime = null;

  @SerializedName("serviceType")
  private String serviceType = null;

  public ResponseHubServiceType id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID generated by NaaS as part of hub creation. NaaS generated attribute.
   * @return id
  **/
  @Schema(required = true, description = "Unique ID generated by NaaS as part of hub creation. NaaS generated attribute.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResponseHubServiceType callback(String callback) {
    this.callback = callback;
    return this;
  }

   /**
   * communication endpoint address provided by consumer who is subscribing to recieve events or notifications.
   * @return callback
  **/
  @Schema(required = true, description = "communication endpoint address provided by consumer who is subscribing to recieve events or notifications.")
  public String getCallback() {
    return callback;
  }

  public void setCallback(String callback) {
    this.callback = callback;
  }

  public ResponseHubServiceType eventType(String eventType) {
    this.eventType = eventType;
    return this;
  }

   /**
   * Event to which a consumer wants to subscribe
   * @return eventType
  **/
  @Schema(required = true, description = "Event to which a consumer wants to subscribe")
  public String getEventType() {
    return eventType;
  }

  public void setEventType(String eventType) {
    this.eventType = eventType;
  }

  public ResponseHubServiceType createdTime(String createdTime) {
    this.createdTime = createdTime;
    return this;
  }

   /**
   * Date when the subscription was created. DateTime Format should be ISO-8601 (e.g. 2018-06-21T04:17:48+00:00)
   * @return createdTime
  **/
  @Schema(required = true, description = "Date when the subscription was created. DateTime Format should be ISO-8601 (e.g. 2018-06-21T04:17:48+00:00)")
  public String getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(String createdTime) {
    this.createdTime = createdTime;
  }

  public ResponseHubServiceType serviceType(String serviceType) {
    this.serviceType = serviceType;
    return this;
  }

   /**
   * serviceType for which the subscription is made
   * @return serviceType
  **/
  @Schema(required = true, description = "serviceType for which the subscription is made")
  public String getServiceType() {
    return serviceType;
  }

  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseHubServiceType responseHubServiceType = (ResponseHubServiceType) o;
    return Objects.equals(this.id, responseHubServiceType.id) &&
        Objects.equals(this.callback, responseHubServiceType.callback) &&
        Objects.equals(this.eventType, responseHubServiceType.eventType) &&
        Objects.equals(this.createdTime, responseHubServiceType.createdTime) &&
        Objects.equals(this.serviceType, responseHubServiceType.serviceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, callback, eventType, createdTime, serviceType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseHubServiceType {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    callback: ").append(toIndentedString(callback)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
