/*
 * MobileAccess v1.3.0
 *  ##### **NaaS API Version:** 2.4.0 ##### **mobileAccess service version:** 1.2.3 ## OVERVIEW TMF 640 - Activation and Configuration API. This is a strategic mobileAccess service aiming to provide network capabilities to products.   **Note: Enum values are case sensitive**
 *
 * OpenAPI spec version: 2.4.5
 * Contact: D1701045@team.telstra.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.client.model.ServiceAcknowledgement;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Model to capture the sample response for http 202 response.
 */
@Schema(description = "Model to capture the sample response for http 202 response.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-13T11:27:23.768Z[GMT]")
public class ServiceAcknowledgement {
  @SerializedName("id")
  private String id = null;

  @SerializedName("href")
  private String href = null;

  public ServiceAcknowledgement id(String id) {
    this.id = id;
    return this;
  }

   /**
   * This should be a UUID created by Domain. Identifier of a Service Instance. Required to be unique. Used in URIs as the identifier of the Service Instance (for modify or delete use cases).
   * @return id
  **/
  @Schema(required = true, description = "This should be a UUID created by Domain. Identifier of a Service Instance. Required to be unique. Used in URIs as the identifier of the Service Instance (for modify or delete use cases).")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ServiceAcknowledgement href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Created by Domain. Reference to the Service Instance (useful for delete or modify methods)
   * @return href
  **/
  @Schema(required = true, description = "Created by Domain. Reference to the Service Instance (useful for delete or modify methods)")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceAcknowledgement serviceAcknowledgement = (ServiceAcknowledgement) o;
    return Objects.equals(this.id, serviceAcknowledgement.id) &&
        Objects.equals(this.href, serviceAcknowledgement.href);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, href);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceAcknowledgement {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
